plone:
  image: eeacms/plone-eea-pdf
  ports:
  - "8080:8080"
  environment:
  - EEADOWNLOADS_NAME=downloads
  - EEADOWNLOADS_PATH=/opt/zope/var/downloads/pdf
  - EEACONVERTER_TEMP=/opt/zope/var/downloads/tmp
  links:
  - postfix
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - data

postfix:
  image: eeacms/postfix
  volumes:
  - /etc/localtime:/etc/localtime:ro
  environment:
  - MTP_HOST=example.com

data:
  image: busybox
  tty: true
  stdin_open: true
  volumes:
  - /opt/zope/var/blobstorage
  - /opt/zope/var/filestorage
  - /opt/zope/var/downloads/pdf
  - /opt/zope/var/downloads/tmp
  command: ["chown", "-v", "-R", "500:500", "/opt/zope/var"]
